title:
  patterns:
    - '(Docs|Breaking|Improvement|Fix|Refactor|Feat):\s[A-Z]*-\d+.*'
    - 'Build:\d+\.\d+\.\d'
      # allow dependabot formatted PRs
    - "(Deps|Deps-dev): .*"
  error: >-
    You have to include [<change-type>:<ticket number>] or Build:X.X.X> into
    your title
body:
  patterns:
    - "[\\s\\S]*\\[x\\] I have implemented all requirements[\\s\\S]*\\[x\\] I am not affecting someone else's work[\\s\\S]*\\[x\\] I have added relevant tests[\\s\\S]*\\[x\\] I have added comments to all the bits that are hard to follow[\\s\\S]*\\[x\\] I have added\/updated Documentation[\\s\\S]*\\[x\\] I have updated the appropriate changelog with a line for my changes[\\s\\S]*"
  error: Found unchecked checkbox, all checkboxes must be checked
version: 1
