[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.6.0"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]
[tool.borg.scripts]
