/**
 * Copyright 2023 Impulse Innovations Limited
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Meta } from '@storybook/react';
import React from 'react';

import { default as MultiSelectComponent, MultiSelectProps } from './multiselect';

export default {
    component: MultiSelectComponent,
    title: 'UI Components/Multi Select',
} as Meta;

const sampleItems = [
    {
        label: 'this is an extremely long label that may overflow',
        value: 'value 1',
    },
    {
        label: 'label 2',
        value: 'value 2',
    },
    {
        label: 'label 3',
        value: 'value 3',
    },
    {
        label: 'label 4',
        value: 'value 4',
    },
    {
        label: 'label 5',
        value: 'value 5',
    },
    {
        label: 'label 6',
        value: 'value 6',
    },
    {
        label: 'label 7',
        value: 'value 7',
    },
    {
        label: 'label 8',
        value: 'value 8',
    },
    {
        label: 'label 9',
        value: 'value 9',
    },
    {
        label: 'label 10',
        value: 'value 10',
    },
    {
        label: 'label 11',
        value: 'value 11',
    },

    {
        label: 'label 12',
        value: 'value 12',
    },
    {
        label: 'label 13',
        value: 'value 13',
    },
    {
        label: 'label 14',
        value: 'value 14',
    },
    {
        label: 'label 15',
        value: 'value 15',
    },
    {
        label: 'label 16',
        value: 'value 16',
    },
    {
        label: 'label 17',
        value: 'value 17',
    },
    {
        label: 'label 18',
        value: 'value 18',
    },
    {
        label: 'label 19',
        value: 'value 19',
    },
    {
        label: 'label 20',
        value: 'value 20',
    },
    {
        label: 'label 21',
        value: 'value 21',
    },
    {
        label: 'label 22',
        value: 'value 22',
    },
    {
        label: 'label 23',
        value: 'value 23',
    },
    {
        label: 'label 24',
        value: 'value 24',
    },
    {
        label: 'label 25',
        value: 'value 25',
    },
    {
        label: 'label 26',
        value: 'value 26',
    },
    {
        label: 'label 27',
        value: 'value 27',
    },
    {
        label: 'label 28',
        value: 'value 28',
    },
    {
        label: 'label 29',
        value: 'value 29',
    },
    {
        label: 'label 30',
        value: 'value 30',
    },
    {
        label: 'label 31',
        value: 'value 31',
    },
    {
        label: 'label 32',
        value: 'value 32',
    },
    {
        label: 'label 33',
        value: 'value 33',
    },
    {
        label: 'label 34',
        value: 'value 34',
    },
    {
        label: 'label 35',
        value: 'value 35',
    },
    {
        label: 'label 36',
        value: 'value 36',
    },
    {
        badge: null,
        image: null,
        label: 'U43926',
        value: 'U43926',
    },
    {
        badge: null,
        image: null,
        label: 'U44110',
        value: 'U44110',
    },
    {
        badge: null,
        image: null,
        label: 'U44136',
        value: 'U44136',
    },
    {
        badge: null,
        image: null,
        label: 'U44138',
        value: 'U44138',
    },
    {
        badge: null,
        image: null,
        label: 'U44155',
        value: 'U44155',
    },
    {
        badge: null,
        image: null,
        label: 'U44159',
        value: 'U44159',
    },
    {
        badge: null,
        image: null,
        label: 'U44179',
        value: 'U44179',
    },
    {
        badge: null,
        image: null,
        label: 'U44180',
        value: 'U44180',
    },
    {
        badge: null,
        image: null,
        label: 'U44182',
        value: 'U44182',
    },
    {
        badge: null,
        image: null,
        label: 'U44210',
        value: 'U44210',
    },
    {
        badge: null,
        image: null,
        label: 'U44220',
        value: 'U44220',
    },
    {
        badge: null,
        image: null,
        label: 'U44229',
        value: 'U44229',
    },
    {
        badge: null,
        image: null,
        label: 'U44252',
        value: 'U44252',
    },
    {
        badge: null,
        image: null,
        label: 'U44253',
        value: 'U44253',
    },
    {
        badge: null,
        image: null,
        label: 'U44262',
        value: 'U44262',
    },
    {
        badge: null,
        image: null,
        label: 'U44538',
        value: 'U44538',
    },
    {
        badge: null,
        image: null,
        label: 'U44724',
        value: 'U44724',
    },
    {
        badge: null,
        image: null,
        label: 'U44728',
        value: 'U44728',
    },
    {
        badge: null,
        image: null,
        label: 'U44734',
        value: 'U44734',
    },
    {
        badge: null,
        image: null,
        label: 'U44769',
        value: 'U44769',
    },
    {
        badge: null,
        image: null,
        label: 'U44818',
        value: 'U44818',
    },
    {
        badge: null,
        image: null,
        label: 'U44954',
        value: 'U44954',
    },
    {
        badge: null,
        image: null,
        label: 'U44981',
        value: 'U44981',
    },
    {
        badge: null,
        image: null,
        label: 'U44982',
        value: 'U44982',
    },
    {
        badge: null,
        image: null,
        label: 'U44983',
        value: 'U44983',
    },
    {
        badge: null,
        image: null,
        label: 'U44987',
        value: 'U44987',
    },
    {
        badge: null,
        image: null,
        label: 'U44997',
        value: 'U44997',
    },
    {
        badge: null,
        image: null,
        label: 'U45315',
        value: 'U45315',
    },
    {
        badge: null,
        image: null,
        label: 'U45316',
        value: 'U45316',
    },
    {
        badge: null,
        image: null,
        label: 'U45624',
        value: 'U45624',
    },
    {
        badge: null,
        image: null,
        label: 'U45655',
        value: 'U45655',
    },
    {
        badge: null,
        image: null,
        label: 'U45660',
        value: 'U45660',
    },
    {
        badge: null,
        image: null,
        label: 'U45674',
        value: 'U45674',
    },
    {
        badge: null,
        image: null,
        label: 'U45757',
        value: 'U45757',
    },
    {
        badge: null,
        image: null,
        label: 'U45758',
        value: 'U45758',
    },
    {
        badge: null,
        image: null,
        label: 'U45759',
        value: 'U45759',
    },
    {
        badge: null,
        image: null,
        label: 'U45760',
        value: 'U45760',
    },
    {
        badge: null,
        image: null,
        label: 'U45797',
        value: 'U45797',
    },
    {
        badge: null,
        image: null,
        label: 'U45872',
        value: 'U45872',
    },
    {
        badge: null,
        image: null,
        label: 'U45912',
        value: 'U45912',
    },
    {
        badge: null,
        image: null,
        label: 'U46050',
        value: 'U46050',
    },
    {
        badge: null,
        image: null,
        label: 'U46051',
        value: 'U46051',
    },
    {
        badge: null,
        image: null,
        label: 'U46085',
        value: 'U46085',
    },
    {
        badge: null,
        image: null,
        label: 'U46086',
        value: 'U46086',
    },
    {
        badge: null,
        image: null,
        label: 'U46100',
        value: 'U46100',
    },
    {
        badge: null,
        image: null,
        label: 'U46101',
        value: 'U46101',
    },
    {
        badge: null,
        image: null,
        label: 'U46184',
        value: 'U46184',
    },
    {
        badge: null,
        image: null,
        label: 'U46516',
        value: 'U46516',
    },
    {
        badge: null,
        image: null,
        label: 'U46518',
        value: 'U46518',
    },
    {
        badge: null,
        image: null,
        label: 'U46670',
        value: 'U46670',
    },
    {
        badge: null,
        image: null,
        label: 'U46999',
        value: 'U46999',
    },
    {
        badge: null,
        image: null,
        label: 'U47007',
        value: 'U47007',
    },
    {
        badge: null,
        image: null,
        label: 'U47023',
        value: 'U47023',
    },
    {
        badge: null,
        image: null,
        label: 'U47041',
        value: 'U47041',
    },
    {
        badge: null,
        image: null,
        label: 'U47046',
        value: 'U47046',
    },
    {
        badge: null,
        image: null,
        label: 'U47061',
        value: 'U47061',
    },
    {
        badge: null,
        image: null,
        label: 'U47062',
        value: 'U47062',
    },
    {
        badge: null,
        image: null,
        label: 'U47063',
        value: 'U47063',
    },
    {
        badge: null,
        image: null,
        label: 'U47073',
        value: 'U47073',
    },
    {
        badge: null,
        image: null,
        label: 'U47080',
        value: 'U47080',
    },
    {
        badge: null,
        image: null,
        label: 'U47090',
        value: 'U47090',
    },
    {
        badge: null,
        image: null,
        label: 'U47093',
        value: 'U47093',
    },
    {
        badge: null,
        image: null,
        label: 'U47122',
        value: 'U47122',
    },
    {
        badge: null,
        image: null,
        label: 'U47290',
        value: 'U47290',
    },
    {
        badge: null,
        image: null,
        label: 'U47293',
        value: 'U47293',
    },
    {
        badge: null,
        image: null,
        label: 'U47569',
        value: 'U47569',
    },
    {
        badge: null,
        image: null,
        label: 'U47601',
        value: 'U47601',
    },
    {
        badge: null,
        image: null,
        label: 'U47868',
        value: 'U47868',
    },
    {
        badge: null,
        image: null,
        label: 'U48485',
        value: 'U48485',
    },
    {
        badge: null,
        image: null,
        label: 'U48489',
        value: 'U48489',
    },
    {
        badge: null,
        image: null,
        label: 'U48506',
        value: 'U48506',
    },
    {
        badge: null,
        image: null,
        label: 'U48537',
        value: 'U48537',
    },
    {
        badge: null,
        image: null,
        label: 'U48643',
        value: 'U48643',
    },
    {
        badge: null,
        image: null,
        label: 'U48644',
        value: 'U48644',
    },
    {
        badge: null,
        image: null,
        label: 'U48645',
        value: 'U48645',
    },
    {
        badge: null,
        image: null,
        label: 'U48687',
        value: 'U48687',
    },
    {
        badge: null,
        image: null,
        label: 'U48886',
        value: 'U48886',
    },
    {
        badge: null,
        image: null,
        label: 'U48902',
        value: 'U48902',
    },
    {
        badge: null,
        image: null,
        label: 'U48914',
        value: 'U48914',
    },
    {
        badge: null,
        image: null,
        label: 'U49185',
        value: 'U49185',
    },
    {
        badge: null,
        image: null,
        label: 'U49211',
        value: 'U49211',
    },
    {
        badge: null,
        image: null,
        label: 'U49302',
        value: 'U49302',
    },
    {
        badge: null,
        image: null,
        label: 'U49341',
        value: 'U49341',
    },
    {
        badge: null,
        image: null,
        label: 'U49449',
        value: 'U49449',
    },
    {
        badge: null,
        image: null,
        label: 'U49450',
        value: 'U49450',
    },
    {
        badge: null,
        image: null,
        label: 'U49451',
        value: 'U49451',
    },
    {
        badge: null,
        image: null,
        label: 'U49470',
        value: 'U49470',
    },
    {
        badge: null,
        image: null,
        label: 'U49544',
        value: 'U49544',
    },
    {
        badge: null,
        image: null,
        label: 'U49546',
        value: 'U49546',
    },
    {
        badge: null,
        image: null,
        label: 'U49553',
        value: 'U49553',
    },
    {
        badge: null,
        image: null,
        label: 'U49753',
        value: 'U49753',
    },
    {
        badge: null,
        image: null,
        label: 'U49940',
        value: 'U49940',
    },
    {
        badge: null,
        image: null,
        label: 'U49978',
        value: 'U49978',
    },
    {
        badge: null,
        image: null,
        label: 'U50021',
        value: 'U50021',
    },
    {
        badge: null,
        image: null,
        label: 'U50081',
        value: 'U50081',
    },
    {
        badge: null,
        image: null,
        label: 'U50082',
        value: 'U50082',
    },
    {
        badge: null,
        image: null,
        label: 'U50083',
        value: 'U50083',
    },
    {
        badge: null,
        image: null,
        label: 'U50085',
        value: 'U50085',
    },
    {
        badge: null,
        image: null,
        label: 'U50086',
        value: 'U50086',
    },
    {
        badge: null,
        image: null,
        label: 'U50376',
        value: 'U50376',
    },
    {
        badge: null,
        image: null,
        label: 'U50429',
        value: 'U50429',
    },
    {
        badge: null,
        image: null,
        label: 'U50521',
        value: 'U50521',
    },
    {
        badge: null,
        image: null,
        label: 'U50544',
        value: 'U50544',
    },
    {
        badge: null,
        image: null,
        label: 'U50545',
        value: 'U50545',
    },
    {
        badge: null,
        image: null,
        label: 'U50552',
        value: 'U50552',
    },
    {
        badge: null,
        image: null,
        label: 'U50557',
        value: 'U50557',
    },
    {
        badge: null,
        image: null,
        label: 'U50558',
        value: 'U50558',
    },
    {
        badge: null,
        image: null,
        label: 'U50559',
        value: 'U50559',
    },
    {
        badge: null,
        image: null,
        label: 'U50562',
        value: 'U50562',
    },
    {
        badge: null,
        image: null,
        label: 'U50583',
        value: 'U50583',
    },
    {
        badge: null,
        image: null,
        label: 'U50585',
        value: 'U50585',
    },
    {
        badge: null,
        image: null,
        label: 'U50587',
        value: 'U50587',
    },
    {
        badge: null,
        image: null,
        label: 'U50716',
        value: 'U50716',
    },
    {
        badge: null,
        image: null,
        label: 'U50721',
        value: 'U50721',
    },
    {
        badge: null,
        image: null,
        label: 'U50722',
        value: 'U50722',
    },
    {
        badge: null,
        image: null,
        label: 'U50723',
        value: 'U50723',
    },
    {
        badge: null,
        image: null,
        label: 'U50724',
        value: 'U50724',
    },
    {
        badge: null,
        image: null,
        label: 'U50725',
        value: 'U50725',
    },
    {
        badge: null,
        image: null,
        label: 'U50726',
        value: 'U50726',
    },
    {
        badge: null,
        image: null,
        label: 'U50727',
        value: 'U50727',
    },
    {
        badge: null,
        image: null,
        label: 'U50738',
        value: 'U50738',
    },
    {
        badge: null,
        image: null,
        label: 'U50747',
        value: 'U50747',
    },
    {
        badge: null,
        image: null,
        label: 'U50777',
        value: 'U50777',
    },
    {
        badge: null,
        image: null,
        label: 'U51047',
        value: 'U51047',
    },
    {
        badge: null,
        image: null,
        label: 'U51048',
        value: 'U51048',
    },
    {
        badge: null,
        image: null,
        label: 'U51058',
        value: 'U51058',
    },
    {
        badge: null,
        image: null,
        label: 'U51064',
        value: 'U51064',
    },
    {
        badge: null,
        image: null,
        label: 'U51065',
        value: 'U51065',
    },
    {
        badge: null,
        image: null,
        label: 'U51071',
        value: 'U51071',
    },
    {
        badge: null,
        image: null,
        label: 'U51074',
        value: 'U51074',
    },
    {
        badge: null,
        image: null,
        label: 'U51086',
        value: 'U51086',
    },
    {
        badge: null,
        image: null,
        label: 'U51139',
        value: 'U51139',
    },
    {
        badge: null,
        image: null,
        label: 'U51239',
        value: 'U51239',
    },
    {
        badge: null,
        image: null,
        label: 'U51241',
        value: 'U51241',
    },
    {
        badge: null,
        image: null,
        label: 'U51243',
        value: 'U51243',
    },
    {
        badge: null,
        image: null,
        label: 'U51321',
        value: 'U51321',
    },
    {
        badge: null,
        image: null,
        label: 'U51855',
        value: 'U51855',
    },
    {
        badge: null,
        image: null,
        label: 'U52170',
        value: 'U52170',
    },
    {
        badge: null,
        image: null,
        label: 'U52189',
        value: 'U52189',
    },
    {
        badge: null,
        image: null,
        label: 'U52270',
        value: 'U52270',
    },
    {
        badge: null,
        image: null,
        label: 'U52293',
        value: 'U52293',
    },
    {
        badge: null,
        image: null,
        label: 'U52659',
        value: 'U52659',
    },
    {
        badge: null,
        image: null,
        label: 'U52660',
        value: 'U52660',
    },
    {
        badge: null,
        image: null,
        label: 'U52662',
        value: 'U52662',
    },
    {
        badge: null,
        image: null,
        label: 'U52751',
        value: 'U52751',
    },
    {
        badge: null,
        image: null,
        label: 'U52766',
        value: 'U52766',
    },
    {
        badge: null,
        image: null,
        label: 'U52902',
        value: 'U52902',
    },
    {
        badge: null,
        image: null,
        label: 'U52970',
        value: 'U52970',
    },
    {
        badge: null,
        image: null,
        label: 'U53267',
        value: 'U53267',
    },
    {
        badge: null,
        image: null,
        label: 'U53268',
        value: 'U53268',
    },
    {
        badge: null,
        image: null,
        label: 'U53269',
        value: 'U53269',
    },
    {
        badge: null,
        image: null,
        label: 'U53270',
        value: 'U53270',
    },
    {
        badge: null,
        image: null,
        label: 'U53271',
        value: 'U53271',
    },
    {
        badge: null,
        image: null,
        label: 'U53272',
        value: 'U53272',
    },
    {
        badge: null,
        image: null,
        label: 'U53273',
        value: 'U53273',
    },
    {
        badge: null,
        image: null,
        label: 'U53274',
        value: 'U53274',
    },
    {
        badge: null,
        image: null,
        label: 'U53275',
        value: 'U53275',
    },
    {
        badge: null,
        image: null,
        label: 'U53276',
        value: 'U53276',
    },
    {
        badge: null,
        image: null,
        label: 'U53278',
        value: 'U53278',
    },
    {
        badge: null,
        image: null,
        label: 'U53290',
        value: 'U53290',
    },
    {
        badge: null,
        image: null,
        label: 'U53292',
        value: 'U53292',
    },
    {
        badge: null,
        image: null,
        label: 'U53293',
        value: 'U53293',
    },
    {
        badge: null,
        image: null,
        label: 'U53294',
        value: 'U53294',
    },
    {
        badge: null,
        image: null,
        label: 'U53295',
        value: 'U53295',
    },
    {
        badge: null,
        image: null,
        label: 'U53419',
        value: 'U53419',
    },
    {
        badge: null,
        image: null,
        label: 'U53420',
        value: 'U53420',
    },
    {
        badge: null,
        image: null,
        label: 'U53423',
        value: 'U53423',
    },
    {
        badge: null,
        image: null,
        label: 'U53425',
        value: 'U53425',
    },
    {
        badge: null,
        image: null,
        label: 'U53426',
        value: 'U53426',
    },
    {
        badge: null,
        image: null,
        label: 'U53427',
        value: 'U53427',
    },
    {
        badge: null,
        image: null,
        label: 'U53428',
        value: 'U53428',
    },
    {
        badge: null,
        image: null,
        label: 'U53476',
        value: 'U53476',
    },
    {
        badge: null,
        image: null,
        label: 'U53547',
        value: 'U53547',
    },
    {
        badge: null,
        image: null,
        label: 'U53971',
        value: 'U53971',
    },
    {
        badge: null,
        image: null,
        label: 'U54412',
        value: 'U54412',
    },
    {
        badge: null,
        image: null,
        label: 'U54527',
        value: 'U54527',
    },
    {
        badge: null,
        image: null,
        label: 'U54702',
        value: 'U54702',
    },
    {
        badge: null,
        image: null,
        label: 'U54706',
        value: 'U54706',
    },
    {
        badge: null,
        image: null,
        label: 'U54707',
        value: 'U54707',
    },
    {
        badge: null,
        image: null,
        label: 'U54727',
        value: 'U54727',
    },
    {
        badge: null,
        image: null,
        label: 'U54748',
        value: 'U54748',
    },
    {
        badge: null,
        image: null,
        label: 'U54810',
        value: 'U54810',
    },
    {
        badge: null,
        image: null,
        label: 'U54908',
        value: 'U54908',
    },
    {
        badge: null,
        image: null,
        label: 'U55000',
        value: 'U55000',
    },
    {
        badge: null,
        image: null,
        label: 'U55144',
        value: 'U55144',
    },
    {
        badge: null,
        image: null,
        label: 'U55145',
        value: 'U55145',
    },
    {
        badge: null,
        image: null,
        label: 'U55146',
        value: 'U55146',
    },
    {
        badge: null,
        image: null,
        label: 'U55147',
        value: 'U55147',
    },
    {
        badge: null,
        image: null,
        label: 'U55179',
        value: 'U55179',
    },
    {
        badge: null,
        image: null,
        label: 'U55252',
        value: 'U55252',
    },
    {
        badge: null,
        image: null,
        label: 'U55271',
        value: 'U55271',
    },
    {
        badge: null,
        image: null,
        label: 'U55660',
        value: 'U55660',
    },
    {
        badge: null,
        image: null,
        label: 'U55794',
        value: 'U55794',
    },
    {
        badge: null,
        image: null,
        label: 'U55812',
        value: 'U55812',
    },
    {
        badge: null,
        image: null,
        label: 'U55813',
        value: 'U55813',
    },
    {
        badge: null,
        image: null,
        label: 'U55814',
        value: 'U55814',
    },
    {
        badge: null,
        image: null,
        label: 'U55815',
        value: 'U55815',
    },
    {
        badge: null,
        image: null,
        label: 'U55824',
        value: 'U55824',
    },
    {
        badge: null,
        image: null,
        label: 'U55831',
        value: 'U55831',
    },
    {
        badge: null,
        image: null,
        label: 'U55843',
        value: 'U55843',
    },
    {
        badge: null,
        image: null,
        label: 'U55848',
        value: 'U55848',
    },
    {
        badge: null,
        image: null,
        label: 'U56016',
        value: 'U56016',
    },
    {
        badge: null,
        image: null,
        label: 'U56017',
        value: 'U56017',
    },
    {
        badge: null,
        image: null,
        label: 'U56438',
        value: 'U56438',
    },
    {
        badge: null,
        image: null,
        label: 'U56439',
        value: 'U56439',
    },
    {
        badge: null,
        image: null,
        label: 'U56900',
        value: 'U56900',
    },
    {
        badge: null,
        image: null,
        label: 'U57150',
        value: 'U57150',
    },
    {
        badge: null,
        image: null,
        label: 'U57151',
        value: 'U57151',
    },
    {
        badge: null,
        image: null,
        label: 'U57765',
        value: 'U57765',
    },
    {
        badge: null,
        image: null,
        label: 'U57766',
        value: 'U57766',
    },
    {
        badge: null,
        image: null,
        label: 'U57891',
        value: 'U57891',
    },
    {
        badge: null,
        image: null,
        label: 'U59190',
        value: 'U59190',
    },
    {
        badge: null,
        image: null,
        label: 'U59194',
        value: 'U59194',
    },
    {
        badge: null,
        image: null,
        label: 'U59365',
        value: 'U59365',
    },
    {
        badge: null,
        image: null,
        label: 'U59380',
        value: 'U59380',
    },
    {
        badge: null,
        image: null,
        label: 'U59429',
        value: 'U59429',
    },
    {
        badge: null,
        image: null,
        label: 'U59431',
        value: 'U59431',
    },
    {
        badge: null,
        image: null,
        label: 'U59446',
        value: 'U59446',
    },
    {
        badge: null,
        image: null,
        label: 'U59447',
        value: 'U59447',
    },
    {
        badge: null,
        image: null,
        label: 'U59450',
        value: 'U59450',
    },
    {
        badge: null,
        image: null,
        label: 'U59456',
        value: 'U59456',
    },
    {
        badge: null,
        image: null,
        label: 'U59457',
        value: 'U59457',
    },
    {
        badge: null,
        image: null,
        label: 'U59459',
        value: 'U59459',
    },
    {
        badge: null,
        image: null,
        label: 'U59474',
        value: 'U59474',
    },
    {
        badge: null,
        image: null,
        label: 'U59477',
        value: 'U59477',
    },
    {
        badge: null,
        image: null,
        label: 'U59482',
        value: 'U59482',
    },
    {
        badge: null,
        image: null,
        label: 'U59491',
        value: 'U59491',
    },
    {
        badge: null,
        image: null,
        label: 'U59654',
        value: 'U59654',
    },
    {
        badge: null,
        image: null,
        label: 'U59660',
        value: 'U59660',
    },
    {
        badge: null,
        image: null,
        label: 'U59698',
        value: 'U59698',
    },
    {
        badge: null,
        image: null,
        label: 'U59826',
        value: 'U59826',
    },
    {
        badge: null,
        image: null,
        label: 'U59952',
        value: 'U59952',
    },
    {
        badge: null,
        image: null,
        label: 'U59967',
        value: 'U59967',
    },
    {
        badge: null,
        image: null,
        label: 'U60005',
        value: 'U60005',
    },
    {
        badge: null,
        image: null,
        label: 'U60043',
        value: 'U60043',
    },
    {
        badge: null,
        image: null,
        label: 'U60072',
        value: 'U60072',
    },
    {
        badge: null,
        image: null,
        label: 'U60086',
        value: 'U60086',
    },
    {
        badge: null,
        image: null,
        label: 'U60216',
        value: 'U60216',
    },
    {
        badge: null,
        image: null,
        label: 'U60222',
        value: 'U60222',
    },
    {
        badge: null,
        image: null,
        label: 'U60404',
        value: 'U60404',
    },
    {
        badge: null,
        image: null,
        label: 'U60547',
        value: 'U60547',
    },
    {
        badge: null,
        image: null,
        label: 'U60659',
        value: 'U60659',
    },
    {
        badge: null,
        image: null,
        label: 'U60668',
        value: 'U60668',
    },
    {
        badge: null,
        image: null,
        label: 'U60793',
        value: 'U60793',
    },
    {
        badge: null,
        image: null,
        label: 'U60794',
        value: 'U60794',
    },
    {
        badge: null,
        image: null,
        label: 'U60813',
        value: 'U60813',
    },
    {
        badge: null,
        image: null,
        label: 'U60815',
        value: 'U60815',
    },
    {
        badge: null,
        image: null,
        label: 'U60994',
        value: 'U60994',
    },
    {
        badge: null,
        image: null,
        label: 'U61313',
        value: 'U61313',
    },
    {
        badge: null,
        image: null,
        label: 'U61393',
        value: 'U61393',
    },
    {
        badge: null,
        image: null,
        label: 'U61403',
        value: 'U61403',
    },
    {
        badge: null,
        image: null,
        label: 'U61602',
        value: 'U61602',
    },
    {
        badge: null,
        image: null,
        label: 'U61711',
        value: 'U61711',
    },
    {
        badge: null,
        image: null,
        label: 'U61716',
        value: 'U61716',
    },
    {
        badge: null,
        image: null,
        label: 'U61752',
        value: 'U61752',
    },
    {
        badge: null,
        image: null,
        label: 'U61753',
        value: 'U61753',
    },
    {
        badge: null,
        image: null,
        label: 'U62140',
        value: 'U62140',
    },
    {
        badge: null,
        image: null,
        label: 'U62383',
        value: 'U62383',
    },
    {
        badge: null,
        image: null,
        label: 'U62392',
        value: 'U62392',
    },
    {
        badge: null,
        image: null,
        label: 'U62931',
        value: 'U62931',
    },
    {
        badge: null,
        image: null,
        label: 'U63088',
        value: 'U63088',
    },
    {
        badge: null,
        image: null,
        label: 'U63196',
        value: 'U63196',
    },
    {
        badge: null,
        image: null,
        label: 'U63239',
        value: 'U63239',
    },
    {
        badge: null,
        image: null,
        label: 'U63289',
        value: 'U63289',
    },
    {
        badge: null,
        image: null,
        label: 'U63417',
        value: 'U63417',
    },
    {
        badge: null,
        image: null,
        label: 'U63441',
        value: 'U63441',
    },
    {
        badge: null,
        image: null,
        label: 'U63540',
        value: 'U63540',
    },
    {
        badge: null,
        image: null,
        label: 'U63605',
        value: 'U63605',
    },
    {
        badge: null,
        image: null,
        label: 'U63723',
        value: 'U63723',
    },
    {
        badge: null,
        image: null,
        label: 'U63727',
        value: 'U63727',
    },
    {
        badge: null,
        image: null,
        label: 'U63739',
        value: 'U63739',
    },
    {
        badge: null,
        image: null,
        label: 'U63744',
        value: 'U63744',
    },
    {
        badge: null,
        image: null,
        label: 'U63946',
        value: 'U63946',
    },
    {
        badge: null,
        image: null,
        label: 'U63964',
        value: 'U63964',
    },
    {
        badge: null,
        image: null,
        label: 'U64069',
        value: 'U64069',
    },
    {
        badge: null,
        image: null,
        label: 'U64091',
        value: 'U64091',
    },
    {
        badge: null,
        image: null,
        label: 'U64104',
        value: 'U64104',
    },
    {
        badge: null,
        image: null,
        label: 'U64105',
        value: 'U64105',
    },
    {
        badge: null,
        image: null,
        label: 'U64363',
        value: 'U64363',
    },
    {
        badge: null,
        image: null,
        label: 'U64365',
        value: 'U64365',
    },
    {
        badge: null,
        image: null,
        label: 'U64367',
        value: 'U64367',
    },
    {
        badge: null,
        image: null,
        label: 'U64368',
        value: 'U64368',
    },
    {
        badge: null,
        image: null,
        label: 'U64372',
        value: 'U64372',
    },
    {
        badge: null,
        image: null,
        label: 'U64374',
        value: 'U64374',
    },
    {
        badge: null,
        image: null,
        label: 'U64375',
        value: 'U64375',
    },
    {
        badge: null,
        image: null,
        label: 'U64376',
        value: 'U64376',
    },
    {
        badge: null,
        image: null,
        label: 'U64380',
        value: 'U64380',
    },
    {
        badge: null,
        image: null,
        label: 'U64386',
        value: 'U64386',
    },
    {
        badge: null,
        image: null,
        label: 'U64390',
        value: 'U64390',
    },
    {
        badge: null,
        image: null,
        label: 'U64391',
        value: 'U64391',
    },
    {
        badge: null,
        image: null,
        label: 'U64398',
        value: 'U64398',
    },
    {
        badge: null,
        image: null,
        label: 'U64408',
        value: 'U64408',
    },
    {
        badge: null,
        image: null,
        label: 'U64447',
        value: 'U64447',
    },
    {
        badge: null,
        image: null,
        label: 'U64514',
        value: 'U64514',
    },
    {
        badge: null,
        image: null,
        label: 'U64797',
        value: 'U64797',
    },
    {
        badge: null,
        image: null,
        label: 'U64798',
        value: 'U64798',
    },
    {
        badge: null,
        image: null,
        label: 'U64803',
        value: 'U64803',
    },
    {
        badge: null,
        image: null,
        label: 'U64809',
        value: 'U64809',
    },
    {
        badge: null,
        image: null,
        label: 'U64875',
        value: 'U64875',
    },
    {
        badge: null,
        image: null,
        label: 'U64877',
        value: 'U64877',
    },
    {
        badge: null,
        image: null,
        label: 'U64879',
        value: 'U64879',
    },
    {
        badge: null,
        image: null,
        label: 'U64882',
        value: 'U64882',
    },
    {
        badge: null,
        image: null,
        label: 'U64971',
        value: 'U64971',
    },
    {
        badge: null,
        image: null,
        label: 'U64972',
        value: 'U64972',
    },
    {
        badge: null,
        image: null,
        label: 'U64978',
        value: 'U64978',
    },
    {
        badge: null,
        image: null,
        label: 'U65177',
        value: 'U65177',
    },
    {
        badge: null,
        image: null,
        label: 'U65184',
        value: 'U65184',
    },
    {
        badge: null,
        image: null,
        label: 'U65194',
        value: 'U65194',
    },
    {
        badge: null,
        image: null,
        label: 'U65195',
        value: 'U65195',
    },
    {
        badge: null,
        image: null,
        label: 'U65196',
        value: 'U65196',
    },
    {
        badge: null,
        image: null,
        label: 'U65205',
        value: 'U65205',
    },
    {
        badge: null,
        image: null,
        label: 'U65223',
        value: 'U65223',
    },
    {
        badge: null,
        image: null,
        label: 'U65235',
        value: 'U65235',
    },
    {
        badge: null,
        image: null,
        label: 'U65268',
        value: 'U65268',
    },
    {
        badge: null,
        image: null,
        label: 'U65269',
        value: 'U65269',
    },
    {
        badge: null,
        image: null,
        label: 'U65270',
        value: 'U65270',
    },
    {
        badge: null,
        image: null,
        label: 'U65295',
        value: 'U65295',
    },
    {
        badge: null,
        image: null,
        label: 'U65520',
        value: 'U65520',
    },
    {
        badge: null,
        image: null,
        label: 'U65521',
        value: 'U65521',
    },
    {
        badge: null,
        image: null,
        label: 'U65601',
        value: 'U65601',
    },
    {
        badge: null,
        image: null,
        label: 'U65602',
        value: 'U65602',
    },
    {
        badge: null,
        image: null,
        label: 'U65632',
        value: 'U65632',
    },
    {
        badge: null,
        image: null,
        label: 'U65737',
        value: 'U65737',
    },
    {
        badge: null,
        image: null,
        label: 'U65738',
        value: 'U65738',
    },
    {
        badge: null,
        image: null,
        label: 'U65740',
        value: 'U65740',
    },
    {
        badge: null,
        image: null,
        label: 'U65741',
        value: 'U65741',
    },
    {
        badge: null,
        image: null,
        label: 'U65756',
        value: 'U65756',
    },
    {
        badge: null,
        image: null,
        label: 'U65757',
        value: 'U65757',
    },
    {
        badge: null,
        image: null,
        label: 'U65758',
        value: 'U65758',
    },
    {
        badge: null,
        image: null,
        label: 'U65760',
        value: 'U65760',
    },
    {
        badge: null,
        image: null,
        label: 'U65761',
        value: 'U65761',
    },
    {
        badge: null,
        image: null,
        label: 'U65762',
        value: 'U65762',
    },
    {
        badge: null,
        image: null,
        label: 'U65763',
        value: 'U65763',
    },
    {
        badge: null,
        image: null,
        label: 'U65764',
        value: 'U65764',
    },
    {
        badge: null,
        image: null,
        label: 'U65766',
        value: 'U65766',
    },
    {
        badge: null,
        image: null,
        label: 'U65767',
        value: 'U65767',
    },
    {
        badge: null,
        image: null,
        label: 'U65788',
        value: 'U65788',
    },
    {
        badge: null,
        image: null,
        label: 'U65806',
        value: 'U65806',
    },
    {
        badge: null,
        image: null,
        label: 'U65818',
        value: 'U65818',
    },
    {
        badge: null,
        image: null,
        label: 'U65951',
        value: 'U65951',
    },
    {
        badge: null,
        image: null,
        label: 'U65964',
        value: 'U65964',
    },
    {
        badge: null,
        image: null,
        label: 'U65970',
        value: 'U65970',
    },
    {
        badge: null,
        image: null,
        label: 'U66087',
        value: 'U66087',
    },
    {
        badge: null,
        image: null,
        label: 'U66289',
        value: 'U66289',
    },
    {
        badge: null,
        image: null,
        label: 'U66335',
        value: 'U66335',
    },
    {
        badge: null,
        image: null,
        label: 'U66340',
        value: 'U66340',
    },
    {
        badge: null,
        image: null,
        label: 'U66365',
        value: 'U66365',
    },
    {
        badge: null,
        image: null,
        label: 'U66374',
        value: 'U66374',
    },
    {
        badge: null,
        image: null,
        label: 'U66375',
        value: 'U66375',
    },
    {
        badge: null,
        image: null,
        label: 'U66376',
        value: 'U66376',
    },
    {
        badge: null,
        image: null,
        label: 'U66865',
        value: 'U66865',
    },
    {
        badge: null,
        image: null,
        label: 'U67006',
        value: 'U67006',
    },
    {
        badge: null,
        image: null,
        label: 'U67100',
        value: 'U67100',
    },
    {
        badge: null,
        image: null,
        label: 'U67210',
        value: 'U67210',
    },
    {
        badge: null,
        image: null,
        label: 'U67213',
        value: 'U67213',
    },
    {
        badge: null,
        image: null,
        label: 'U67214',
        value: 'U67214',
    },
    {
        badge: null,
        image: null,
        label: 'U67220',
        value: 'U67220',
    },
    {
        badge: null,
        image: null,
        label: 'U67235',
        value: 'U67235',
    },
    {
        badge: null,
        image: null,
        label: 'U67245',
        value: 'U67245',
    },
    {
        badge: null,
        image: null,
        label: 'U67458',
        value: 'U67458',
    },
    {
        badge: null,
        image: null,
        label: 'U67545',
        value: 'U67545',
    },
    {
        badge: null,
        image: null,
        label: 'U67599',
        value: 'U67599',
    },
    {
        badge: null,
        image: null,
        label: 'U67601',
        value: 'U67601',
    },
    {
        badge: null,
        image: null,
        label: 'U67602',
        value: 'U67602',
    },
    {
        badge: null,
        image: null,
        label: 'U67809',
        value: 'U67809',
    },
    {
        badge: null,
        image: null,
        label: 'U68090',
        value: 'U68090',
    },
    {
        badge: null,
        image: null,
        label: 'U68770',
        value: 'U68770',
    },
    {
        badge: null,
        image: null,
        label: 'U68804',
        value: 'U68804',
    },
    {
        badge: null,
        image: null,
        label: 'U68866',
        value: 'U68866',
    },
    {
        badge: null,
        image: null,
        label: 'U69185',
        value: 'U69185',
    },
    {
        badge: null,
        image: null,
        label: 'U69374',
        value: 'U69374',
    },
    {
        badge: null,
        image: null,
        label: 'U69380',
        value: 'U69380',
    },
    {
        badge: null,
        image: null,
        label: 'U69383',
        value: 'U69383',
    },
    {
        badge: null,
        image: null,
        label: 'U69398',
        value: 'U69398',
    },
    {
        badge: null,
        image: null,
        label: 'U69524',
        value: 'U69524',
    },
    {
        badge: null,
        image: null,
        label: 'U69650',
        value: 'U69650',
    },
    {
        badge: null,
        image: null,
        label: 'U69652',
        value: 'U69652',
    },
    {
        badge: null,
        image: null,
        label: 'U69653',
        value: 'U69653',
    },
    {
        badge: null,
        image: null,
        label: 'U69663',
        value: 'U69663',
    },
    {
        badge: null,
        image: null,
        label: 'U69867',
        value: 'U69867',
    },
    {
        badge: null,
        image: null,
        label: 'U69945',
        value: 'U69945',
    },
    {
        badge: null,
        image: null,
        label: 'U69952',
        value: 'U69952',
    },
    {
        badge: null,
        image: null,
        label: 'U70120',
        value: 'U70120',
    },
    {
        badge: null,
        image: null,
        label: 'U70274',
        value: 'U70274',
    },
    {
        badge: null,
        image: null,
        label: 'U70306',
        value: 'U70306',
    },
    {
        badge: null,
        image: null,
        label: 'U70489',
        value: 'U70489',
    },
    {
        badge: null,
        image: null,
        label: 'U70490',
        value: 'U70490',
    },
    {
        badge: null,
        image: null,
        label: 'U70751',
        value: 'U70751',
    },
    {
        badge: null,
        image: null,
        label: 'U70752',
        value: 'U70752',
    },
    {
        badge: null,
        image: null,
        label: 'U70933',
        value: 'U70933',
    },
    {
        badge: null,
        image: null,
        label: 'U70938',
        value: 'U70938',
    },
    {
        badge: null,
        image: null,
        label: 'U70944',
        value: 'U70944',
    },
    {
        badge: null,
        image: null,
        label: 'U70946',
        value: 'U70946',
    },
    {
        badge: null,
        image: null,
        label: 'U71031',
        value: 'U71031',
    },
    {
        badge: null,
        image: null,
        label: 'U71033',
        value: 'U71033',
    },
    {
        badge: null,
        image: null,
        label: 'U71114',
        value: 'U71114',
    },
    {
        badge: null,
        image: null,
        label: 'U71115',
        value: 'U71115',
    },
    {
        badge: null,
        image: null,
        label: 'U71116',
        value: 'U71116',
    },
    {
        badge: null,
        image: null,
        label: 'U71117',
        value: 'U71117',
    },
    {
        badge: null,
        image: null,
        label: 'U71136',
        value: 'U71136',
    },
    {
        badge: null,
        image: null,
        label: 'U71165',
        value: 'U71165',
    },
    {
        badge: null,
        image: null,
        label: 'U71166',
        value: 'U71166',
    },
    {
        badge: null,
        image: null,
        label: 'U71361',
        value: 'U71361',
    },
    {
        badge: null,
        image: null,
        label: 'U71374',
        value: 'U71374',
    },
    {
        badge: null,
        image: null,
        label: 'U71438',
        value: 'U71438',
    },
    {
        badge: null,
        image: null,
        label: 'U71539',
        value: 'U71539',
    },
    {
        badge: null,
        image: null,
        label: 'U72042',
        value: 'U72042',
    },
    {
        badge: null,
        image: null,
        label: 'U72043',
        value: 'U72043',
    },
    {
        badge: null,
        image: null,
        label: 'U72251',
        value: 'U72251',
    },
    {
        badge: null,
        image: null,
        label: 'U72303',
        value: 'U72303',
    },
    {
        badge: null,
        image: null,
        label: 'U72350',
        value: 'U72350',
    },
    {
        badge: null,
        image: null,
        label: 'U72485',
        value: 'U72485',
    },
    {
        badge: null,
        image: null,
        label: 'U72487',
        value: 'U72487',
    },
    {
        badge: null,
        image: null,
        label: 'U72492',
        value: 'U72492',
    },
    {
        badge: null,
        image: null,
        label: 'U72493',
        value: 'U72493',
    },
    {
        badge: null,
        image: null,
        label: 'U72533',
        value: 'U72533',
    },
    {
        badge: null,
        image: null,
        label: 'U72808',
        value: 'U72808',
    },
    {
        badge: null,
        image: null,
        label: 'U72962',
        value: 'U72962',
    },
    {
        badge: null,
        image: null,
        label: 'U72967',
        value: 'U72967',
    },
    {
        badge: null,
        image: null,
        label: 'U72972',
        value: 'U72972',
    },
    {
        badge: null,
        image: null,
        label: 'U72991',
        value: 'U72991',
    },
    {
        badge: null,
        image: null,
        label: 'U73087',
        value: 'U73087',
    },
    {
        badge: null,
        image: null,
        label: 'U73095',
        value: 'U73095',
    },
    {
        badge: null,
        image: null,
        label: 'U73097',
        value: 'U73097',
    },
    {
        badge: null,
        image: null,
        label: 'U73113',
        value: 'U73113',
    },
    {
        badge: null,
        image: null,
        label: 'U73118',
        value: 'U73118',
    },
    {
        badge: null,
        image: null,
        label: 'U73587',
        value: 'U73587',
    },
    {
        badge: null,
        image: null,
        label: 'U73590',
        value: 'U73590',
    },
    {
        badge: null,
        image: null,
        label: 'U73835',
        value: 'U73835',
    },
    {
        badge: null,
        image: null,
        label: 'U74070',
        value: 'U74070',
    },
    {
        badge: null,
        image: null,
        label: 'U74081',
        value: 'U74081',
    },
    {
        badge: null,
        image: null,
        label: 'U74085',
        value: 'U74085',
    },
    {
        badge: null,
        image: null,
        label: 'U74111',
        value: 'U74111',
    },
    {
        badge: null,
        image: null,
        label: 'U74120',
        value: 'U74120',
    },
    {
        badge: null,
        image: null,
        label: 'U74122',
        value: 'U74122',
    },
    {
        badge: null,
        image: null,
        label: 'U74134',
        value: 'U74134',
    },
    {
        badge: null,
        image: null,
        label: 'U74196',
        value: 'U74196',
    },
    {
        badge: null,
        image: null,
        label: 'U74209',
        value: 'U74209',
    },
    {
        badge: null,
        image: null,
        label: 'U74294',
        value: 'U74294',
    },
    {
        badge: null,
        image: null,
        label: 'U74399',
        value: 'U74399',
    },
    {
        badge: null,
        image: null,
        label: 'U74412',
        value: 'U74412',
    },
    {
        badge: null,
        image: null,
        label: 'U74413',
        value: 'U74413',
    },
    {
        badge: null,
        image: null,
        label: 'U74414',
        value: 'U74414',
    },
    {
        badge: null,
        image: null,
        label: 'U74417',
        value: 'U74417',
    },
    {
        badge: null,
        image: null,
        label: 'U74563',
        value: 'U74563',
    },
    {
        badge: null,
        image: null,
        label: 'U74565',
        value: 'U74565',
    },
    {
        badge: null,
        image: null,
        label: 'U74572',
        value: 'U74572',
    },
    {
        badge: null,
        image: null,
        label: 'U74578',
        value: 'U74578',
    },
    {
        badge: null,
        image: null,
        label: 'U74589',
        value: 'U74589',
    },
    {
        badge: null,
        image: null,
        label: 'U74595',
        value: 'U74595',
    },
    {
        badge: null,
        image: null,
        label: 'U74857',
        value: 'U74857',
    },
    {
        badge: null,
        image: null,
        label: 'U74858',
        value: 'U74858',
    },
    {
        badge: null,
        image: null,
        label: 'U74932',
        value: 'U74932',
    },
    {
        badge: null,
        image: null,
        label: 'U75034',
        value: 'U75034',
    },
    {
        badge: null,
        image: null,
        label: 'U75071',
        value: 'U75071',
    },
    {
        badge: null,
        image: null,
        label: 'U75072',
        value: 'U75072',
    },
    {
        badge: null,
        image: null,
        label: 'U75074',
        value: 'U75074',
    },
    {
        badge: null,
        image: null,
        label: 'U75198',
        value: 'U75198',
    },
    {
        badge: null,
        image: null,
        label: 'U75402',
        value: 'U75402',
    },
    {
        badge: null,
        image: null,
        label: 'U75868',
        value: 'U75868',
    },
    {
        badge: null,
        image: null,
        label: 'U76012',
        value: 'U76012',
    },
    {
        badge: null,
        image: null,
        label: 'U76025',
        value: 'U76025',
    },
    {
        badge: null,
        image: null,
        label: 'U76027',
        value: 'U76027',
    },
    {
        badge: null,
        image: null,
        label: 'U76028',
        value: 'U76028',
    },
    {
        badge: null,
        image: null,
        label: 'U76040',
        value: 'U76040',
    },
    {
        badge: null,
        image: null,
        label: 'U76089',
        value: 'U76089',
    },
    {
        badge: null,
        image: null,
        label: 'U76299',
        value: 'U76299',
    },
    {
        badge: null,
        image: null,
        label: 'U76300',
        value: 'U76300',
    },
    {
        badge: null,
        image: null,
        label: 'U76302',
        value: 'U76302',
    },
    {
        badge: null,
        image: null,
        label: 'U76478',
        value: 'U76478',
    },
    {
        badge: null,
        image: null,
        label: 'U76515',
        value: 'U76515',
    },
    {
        badge: null,
        image: null,
        label: 'U76836',
        value: 'U76836',
    },
    {
        badge: null,
        image: null,
        label: 'U77050',
        value: 'U77050',
    },
    {
        badge: null,
        image: null,
        label: 'U77089',
        value: 'U77089',
    },
    {
        badge: null,
        image: null,
        label: 'U77158',
        value: 'U77158',
    },
    {
        badge: null,
        image: null,
        label: 'U77161',
        value: 'U77161',
    },
    {
        badge: null,
        image: null,
        label: 'U77162',
        value: 'U77162',
    },
    {
        badge: null,
        image: null,
        label: 'U77163',
        value: 'U77163',
    },
    {
        badge: null,
        image: null,
        label: 'U77164',
        value: 'U77164',
    },
    {
        badge: null,
        image: null,
        label: 'U77194',
        value: 'U77194',
    },
    {
        badge: null,
        image: null,
        label: 'U77358',
        value: 'U77358',
    },
    {
        badge: null,
        image: null,
        label: 'U77387',
        value: 'U77387',
    },
    {
        badge: null,
        image: null,
        label: 'U77401',
        value: 'U77401',
    },
    {
        badge: null,
        image: null,
        label: 'U77404',
        value: 'U77404',
    },
    {
        badge: null,
        image: null,
        label: 'U77405',
        value: 'U77405',
    },
    {
        badge: null,
        image: null,
        label: 'U77745',
        value: 'U77745',
    },
    {
        badge: null,
        image: null,
        label: 'U77899',
        value: 'U77899',
    },
    {
        badge: null,
        image: null,
        label: 'U78076',
        value: 'U78076',
    },
    {
        badge: null,
        image: null,
        label: 'U78324',
        value: 'U78324',
    },
    {
        badge: null,
        image: null,
        label: 'U78325',
        value: 'U78325',
    },
    {
        badge: null,
        image: null,
        label: 'U78427',
        value: 'U78427',
    },
    {
        badge: null,
        image: null,
        label: 'U78575',
        value: 'U78575',
    },
    {
        badge: null,
        image: null,
        label: 'U78599',
        value: 'U78599',
    },
    {
        badge: null,
        image: null,
        label: 'U78662',
        value: 'U78662',
    },
    {
        badge: null,
        image: null,
        label: 'U79397',
        value: 'U79397',
    },
    {
        badge: null,
        image: null,
        label: 'U80163',
        value: 'U80163',
    },
    {
        badge: null,
        image: null,
        label: 'U80208',
        value: 'U80208',
    },
    {
        badge: null,
        image: null,
        label: 'U80213',
        value: 'U80213',
    },
    {
        badge: null,
        image: null,
        label: 'U80215',
        value: 'U80215',
    },
    {
        badge: null,
        image: null,
        label: 'U80292',
        value: 'U80292',
    },
    {
        badge: null,
        image: null,
        label: 'U80501',
        value: 'U80501',
    },
    {
        badge: null,
        image: null,
        label: 'U80504',
        value: 'U80504',
    },
    {
        badge: null,
        image: null,
        label: 'U80505',
        value: 'U80505',
    },
    {
        badge: null,
        image: null,
        label: 'U80806',
        value: 'U80806',
    },
    {
        badge: null,
        image: null,
        label: 'U80965',
        value: 'U80965',
    },
    {
        badge: null,
        image: null,
        label: 'U81229',
        value: 'U81229',
    },
    {
        badge: null,
        image: null,
        label: 'U81231',
        value: 'U81231',
    },
    {
        badge: null,
        image: null,
        label: 'U81419',
        value: 'U81419',
    },
    {
        badge: null,
        image: null,
        label: 'U81420',
        value: 'U81420',
    },
    {
        badge: null,
        image: null,
        label: 'U81426',
        value: 'U81426',
    },
    {
        badge: null,
        image: null,
        label: 'U81427',
        value: 'U81427',
    },
    {
        badge: null,
        image: null,
        label: 'U81434',
        value: 'U81434',
    },
    {
        badge: null,
        image: null,
        label: 'U81439',
        value: 'U81439',
    },
    {
        badge: null,
        image: null,
        label: 'U81441',
        value: 'U81441',
    },
    {
        badge: null,
        image: null,
        label: 'U81447',
        value: 'U81447',
    },
    {
        badge: null,
        image: null,
        label: 'U81448',
        value: 'U81448',
    },
    {
        badge: null,
        image: null,
        label: 'U81449',
        value: 'U81449',
    },
    {
        badge: null,
        image: null,
        label: 'U81925',
        value: 'U81925',
    },
    {
        badge: null,
        image: null,
        label: 'U82052',
        value: 'U82052',
    },
    {
        badge: null,
        image: null,
        label: 'U82053',
        value: 'U82053',
    },
    {
        badge: null,
        image: null,
        label: 'U82143',
        value: 'U82143',
    },
    {
        badge: null,
        image: null,
        label: 'U82147',
        value: 'U82147',
    },
    {
        badge: null,
        image: null,
        label: 'U82148',
        value: 'U82148',
    },
    {
        badge: null,
        image: null,
        label: 'U82329',
        value: 'U82329',
    },
    {
        badge: null,
        image: null,
        label: 'U82384',
        value: 'U82384',
    },
    {
        badge: null,
        image: null,
        label: 'U82386',
        value: 'U82386',
    },
    {
        badge: null,
        image: null,
        label: 'U82531',
        value: 'U82531',
    },
    {
        badge: null,
        image: null,
        label: 'U82549',
        value: 'U82549',
    },
    {
        badge: null,
        image: null,
        label: 'U82553',
        value: 'U82553',
    },
    {
        badge: null,
        image: null,
        label: 'U82594',
        value: 'U82594',
    },
    {
        badge: null,
        image: null,
        label: 'U82596',
        value: 'U82596',
    },
    {
        badge: null,
        image: null,
        label: 'U82632',
        value: 'U82632',
    },
    {
        badge: null,
        image: null,
        label: 'U82737',
        value: 'U82737',
    },
    {
        badge: null,
        image: null,
        label: 'U82781',
        value: 'U82781',
    },
    {
        badge: null,
        image: null,
        label: 'U82815',
        value: 'U82815',
    },
    {
        badge: null,
        image: null,
        label: 'U82816',
        value: 'U82816',
    },
    {
        badge: null,
        image: null,
        label: 'U82871',
        value: 'U82871',
    },
    {
        badge: null,
        image: null,
        label: 'U82919',
        value: 'U82919',
    },
    {
        badge: null,
        image: null,
        label: 'U82926',
        value: 'U82926',
    },
    {
        badge: null,
        image: null,
        label: 'U83177',
        value: 'U83177',
    },
    {
        badge: null,
        image: null,
        label: 'U83178',
        value: 'U83178',
    },
    {
        badge: null,
        image: null,
        label: 'U83180',
        value: 'U83180',
    },
    {
        badge: null,
        image: null,
        label: 'U83181',
        value: 'U83181',
    },
    {
        badge: null,
        image: null,
        label: 'U83182',
        value: 'U83182',
    },
    {
        badge: null,
        image: null,
        label: 'U83183',
        value: 'U83183',
    },
    {
        badge: null,
        image: null,
        label: 'U83184',
        value: 'U83184',
    },
    {
        badge: null,
        image: null,
        label: 'U83185',
        value: 'U83185',
    },
    {
        badge: null,
        image: null,
        label: 'U83186',
        value: 'U83186',
    },
    {
        badge: null,
        image: null,
        label: 'U83418',
        value: 'U83418',
    },
    {
        badge: null,
        image: null,
        label: 'U83430',
        value: 'U83430',
    },
    {
        badge: null,
        image: null,
        label: 'U83540',
        value: 'U83540',
    },
    {
        badge: null,
        image: null,
        label: 'U83619',
        value: 'U83619',
    },
    {
        badge: null,
        image: null,
        label: 'U83625',
        value: 'U83625',
    },
    {
        badge: null,
        image: null,
        label: 'U83760',
        value: 'U83760',
    },
    {
        badge: null,
        image: null,
        label: 'U83769',
        value: 'U83769',
    },
    {
        badge: null,
        image: null,
        label: 'U84136',
        value: 'U84136',
    },
    {
        badge: null,
        image: null,
        label: 'U84275',
        value: 'U84275',
    },
    {
        badge: null,
        image: null,
        label: 'U84357',
        value: 'U84357',
    },
    {
        badge: null,
        image: null,
        label: 'U84358',
        value: 'U84358',
    },
    {
        badge: null,
        image: null,
        label: 'U84372',
        value: 'U84372',
    },
    {
        badge: null,
        image: null,
        label: 'U84373',
        value: 'U84373',
    },
    {
        badge: null,
        image: null,
        label: 'U84399',
        value: 'U84399',
    },
    {
        badge: null,
        image: null,
        label: 'U84434',
        value: 'U84434',
    },
    {
        badge: null,
        image: null,
        label: 'U84435',
        value: 'U84435',
    },
    {
        badge: null,
        image: null,
        label: 'U84436',
        value: 'U84436',
    },
    {
        badge: null,
        image: null,
        label: 'U84438',
        value: 'U84438',
    },
    {
        badge: null,
        image: null,
        label: 'U84470',
        value: 'U84470',
    },
    {
        badge: null,
        image: null,
        label: 'U84491',
        value: 'U84491',
    },
    {
        badge: null,
        image: null,
        label: 'U84492',
        value: 'U84492',
    },
    {
        badge: null,
        image: null,
        label: 'U84520',
        value: 'U84520',
    },
    {
        badge: null,
        image: null,
        label: 'U84521',
        value: 'U84521',
    },
    {
        badge: null,
        image: null,
        label: 'U84522',
        value: 'U84522',
    },
    {
        badge: null,
        image: null,
        label: 'U84533',
        value: 'U84533',
    },
    {
        badge: null,
        image: null,
        label: 'U84566',
        value: 'U84566',
    },
    {
        badge: null,
        image: null,
        label: 'U84676',
        value: 'U84676',
    },
    {
        badge: null,
        image: null,
        label: 'U84679',
        value: 'U84679',
    },
    {
        badge: null,
        image: null,
        label: 'U84694',
        value: 'U84694',
    },
    {
        badge: null,
        image: null,
        label: 'U84699',
        value: 'U84699',
    },
    {
        badge: null,
        image: null,
        label: 'U84718',
        value: 'U84718',
    },
    {
        badge: null,
        image: null,
        label: 'U84719',
        value: 'U84719',
    },
    {
        badge: null,
        image: null,
        label: 'U84831',
        value: 'U84831',
    },
    {
        badge: null,
        image: null,
        label: 'U84923',
        value: 'U84923',
    },
    {
        badge: null,
        image: null,
        label: 'U85029',
        value: 'U85029',
    },
    {
        badge: null,
        image: null,
        label: 'U85039',
        value: 'U85039',
    },
    {
        badge: null,
        image: null,
        label: 'U85112',
        value: 'U85112',
    },
    {
        badge: null,
        image: null,
        label: 'U85263',
        value: 'U85263',
    },
    {
        badge: null,
        image: null,
        label: 'U85264',
        value: 'U85264',
    },
    {
        badge: null,
        image: null,
        label: 'U85265',
        value: 'U85265',
    },
    {
        badge: null,
        image: null,
        label: 'U85272',
        value: 'U85272',
    },
    {
        badge: null,
        image: null,
        label: 'U85274',
        value: 'U85274',
    },
    {
        badge: null,
        image: null,
        label: 'U85313',
        value: 'U85313',
    },
    {
        badge: null,
        image: null,
        label: 'U85396',
        value: 'U85396',
    },
    {
        badge: null,
        image: null,
        label: 'U85622',
        value: 'U85622',
    },
    {
        badge: null,
        image: null,
        label: 'U85623',
        value: 'U85623',
    },
    {
        badge: null,
        image: null,
        label: 'U85643',
        value: 'U85643',
    },
    {
        badge: null,
        image: null,
        label: 'U85645',
        value: 'U85645',
    },
    {
        badge: null,
        image: null,
        label: 'U85667',
        value: 'U85667',
    },
    {
        badge: null,
        image: null,
        label: 'U85668',
        value: 'U85668',
    },
    {
        badge: null,
        image: null,
        label: 'U85688',
        value: 'U85688',
    },
    {
        badge: null,
        image: null,
        label: 'U85785',
        value: 'U85785',
    },
    {
        badge: null,
        image: null,
        label: 'U86086',
        value: 'U86086',
    },
    {
        badge: null,
        image: null,
        label: 'U86103',
        value: 'U86103',
    },
    {
        badge: null,
        image: null,
        label: 'U86106',
        value: 'U86106',
    },
    {
        badge: null,
        image: null,
        label: 'U86118',
        value: 'U86118',
    },
    {
        badge: null,
        image: null,
        label: 'U86119',
        value: 'U86119',
    },
    {
        badge: null,
        image: null,
        label: 'U86475',
        value: 'U86475',
    },
    {
        badge: null,
        image: null,
        label: 'U86580',
        value: 'U86580',
    },
    {
        badge: null,
        image: null,
        label: 'U86582',
        value: 'U86582',
    },
    {
        badge: null,
        image: null,
        label: 'U86859',
        value: 'U86859',
    },
    {
        badge: null,
        image: null,
        label: 'U86862',
        value: 'U86862',
    },
    {
        badge: null,
        image: null,
        label: 'U86935',
        value: 'U86935',
    },
    {
        badge: null,
        image: null,
        label: 'U87001',
        value: 'U87001',
    },
    {
        badge: null,
        image: null,
        label: 'U87002',
        value: 'U87002',
    },
    {
        badge: null,
        image: null,
        label: 'U87003',
        value: 'U87003',
    },
    {
        badge: null,
        image: null,
        label: 'U87004',
        value: 'U87004',
    },
    {
        badge: null,
        image: null,
        label: 'U87031',
        value: 'U87031',
    },
    {
        badge: null,
        image: null,
        label: 'U87032',
        value: 'U87032',
    },
    {
        badge: null,
        image: null,
        label: 'U87037',
        value: 'U87037',
    },
    {
        badge: null,
        image: null,
        label: 'U87043',
        value: 'U87043',
    },
    {
        badge: null,
        image: null,
        label: 'U87044',
        value: 'U87044',
    },
    {
        badge: null,
        image: null,
        label: 'U87045',
        value: 'U87045',
    },
    {
        badge: null,
        image: null,
        label: 'U87250',
        value: 'U87250',
    },
    {
        badge: null,
        image: null,
        label: 'U87390',
        value: 'U87390',
    },
    {
        badge: null,
        image: null,
        label: 'U87420',
        value: 'U87420',
    },
    {
        badge: null,
        image: null,
        label: 'U87549',
        value: 'U87549',
    },
    {
        badge: null,
        image: null,
        label: 'U87550',
        value: 'U87550',
    },
    {
        badge: null,
        image: null,
        label: 'U87561',
        value: 'U87561',
    },
    {
        badge: null,
        image: null,
        label: 'U87608',
        value: 'U87608',
    },
    {
        badge: null,
        image: null,
        label: 'U87609',
        value: 'U87609',
    },
    {
        badge: null,
        image: null,
        label: 'U87629',
        value: 'U87629',
    },
    {
        badge: null,
        image: null,
        label: 'U87631',
        value: 'U87631',
    },
    {
        badge: null,
        image: null,
        label: 'U87971',
        value: 'U87971',
    },
    {
        badge: null,
        image: null,
        label: 'U88038',
        value: 'U88038',
    },
    {
        badge: null,
        image: null,
        label: 'U88211',
        value: 'U88211',
    },
    {
        badge: null,
        image: null,
        label: 'U88346',
        value: 'U88346',
    },
    {
        badge: null,
        image: null,
        label: 'U88355',
        value: 'U88355',
    },
    {
        badge: null,
        image: null,
        label: 'U88356',
        value: 'U88356',
    },
    {
        badge: null,
        image: null,
        label: 'U88369',
        value: 'U88369',
    },
    {
        badge: null,
        image: null,
        label: 'U88375',
        value: 'U88375',
    },
    {
        badge: null,
        image: null,
        label: 'U88376',
        value: 'U88376',
    },
    {
        badge: null,
        image: null,
        label: 'U88378',
        value: 'U88378',
    },
    {
        badge: null,
        image: null,
        label: 'U88379',
        value: 'U88379',
    },
    {
        badge: null,
        image: null,
        label: 'U88380',
        value: 'U88380',
    },
    {
        badge: null,
        image: null,
        label: 'U88381',
        value: 'U88381',
    },
    {
        badge: null,
        image: null,
        label: 'U88387',
        value: 'U88387',
    },
    {
        badge: null,
        image: null,
        label: 'U88388',
        value: 'U88388',
    },
    {
        badge: null,
        image: null,
        label: 'U88389',
        value: 'U88389',
    },
    {
        badge: null,
        image: null,
        label: 'U88390',
        value: 'U88390',
    },
    {
        badge: null,
        image: null,
        label: 'U88394',
        value: 'U88394',
    },
    {
        badge: null,
        image: null,
        label: 'U88403',
        value: 'U88403',
    },
    {
        badge: null,
        image: null,
        label: 'U88404',
        value: 'U88404',
    },
    {
        badge: null,
        image: null,
        label: 'U88727',
        value: 'U88727',
    },
    {
        badge: null,
        image: null,
        label: 'U88732',
        value: 'U88732',
    },
    {
        badge: null,
        image: null,
        label: 'U88740',
        value: 'U88740',
    },
    {
        badge: null,
        image: null,
        label: 'U88766',
        value: 'U88766',
    },
    {
        badge: null,
        image: null,
        label: 'U88774',
        value: 'U88774',
    },
    {
        badge: null,
        image: null,
        label: 'U88808',
        value: 'U88808',
    },
    {
        badge: null,
        image: null,
        label: 'U88852',
        value: 'U88852',
    },
    {
        badge: null,
        image: null,
        label: 'U88855',
        value: 'U88855',
    },
    {
        badge: null,
        image: null,
        label: 'U88857',
        value: 'U88857',
    },
    {
        badge: null,
        image: null,
        label: 'U88860',
        value: 'U88860',
    },
    {
        badge: null,
        image: null,
        label: 'U88863',
        value: 'U88863',
    },
    {
        badge: null,
        image: null,
        label: 'U88868',
        value: 'U88868',
    },
    {
        badge: null,
        image: null,
        label: 'U88869',
        value: 'U88869',
    },
    {
        badge: null,
        image: null,
        label: 'U88870',
        value: 'U88870',
    },
    {
        badge: null,
        image: null,
        label: 'U88874',
        value: 'U88874',
    },
    {
        badge: null,
        image: null,
        label: 'U89103',
        value: 'U89103',
    },
    {
        badge: null,
        image: null,
        label: 'U89105',
        value: 'U89105',
    },
    {
        badge: null,
        image: null,
        label: 'U89119',
        value: 'U89119',
    },
    {
        badge: null,
        image: null,
        label: 'U89315',
        value: 'U89315',
    },
    {
        badge: null,
        image: null,
        label: 'U89405',
        value: 'U89405',
    },
    {
        badge: null,
        image: null,
        label: 'U89512',
        value: 'U89512',
    },
    {
        badge: null,
        image: null,
        label: 'U89552',
        value: 'U89552',
    },
    {
        badge: null,
        image: null,
        label: 'U89956',
        value: 'U89956',
    },
    {
        badge: null,
        image: null,
        label: 'U90325',
        value: 'U90325',
    },
    {
        badge: null,
        image: null,
        label: 'U90367',
        value: 'U90367',
    },
    {
        badge: null,
        image: null,
        label: 'U90385',
        value: 'U90385',
    },
    {
        badge: null,
        image: null,
        label: 'U90406',
        value: 'U90406',
    },
    {
        badge: null,
        image: null,
        label: 'U90545',
        value: 'U90545',
    },
    {
        badge: null,
        image: null,
        label: 'U90546',
        value: 'U90546',
    },
    {
        badge: null,
        image: null,
        label: 'U90617',
        value: 'U90617',
    },
    {
        badge: null,
        image: null,
        label: 'U90620',
        value: 'U90620',
    },
    {
        badge: null,
        image: null,
        label: 'U90659',
        value: 'U90659',
    },
    {
        badge: null,
        image: null,
        label: 'U90661',
        value: 'U90661',
    },
    {
        badge: null,
        image: null,
        label: 'U90717',
        value: 'U90717',
    },
    {
        badge: null,
        image: null,
        label: 'U90775',
        value: 'U90775',
    },
    {
        badge: null,
        image: null,
        label: 'U90791',
        value: 'U90791',
    },
    {
        badge: null,
        image: null,
        label: 'U90799',
        value: 'U90799',
    },
    {
        badge: null,
        image: null,
        label: 'U90803',
        value: 'U90803',
    },
    {
        badge: null,
        image: null,
        label: 'U90915',
        value: 'U90915',
    },
    {
        badge: null,
        image: null,
        label: 'U90917',
        value: 'U90917',
    },
    {
        badge: null,
        image: null,
        label: 'U90921',
        value: 'U90921',
    },
    {
        badge: null,
        image: null,
        label: 'U90935',
        value: 'U90935',
    },
    {
        badge: null,
        image: null,
        label: 'U91018',
        value: 'U91018',
    },
    {
        badge: null,
        image: null,
        label: 'U91033',
        value: 'U91033',
    },
    {
        badge: null,
        image: null,
        label: 'U91125',
        value: 'U91125',
    },
    {
        badge: null,
        image: null,
        label: 'U91154',
        value: 'U91154',
    },
    {
        badge: null,
        image: null,
        label: 'U91172',
        value: 'U91172',
    },
    {
        badge: null,
        image: null,
        label: 'U91195',
        value: 'U91195',
    },
    {
        badge: null,
        image: null,
        label: 'U91201',
        value: 'U91201',
    },
    {
        badge: null,
        image: null,
        label: 'U91305',
        value: 'U91305',
    },
    {
        badge: null,
        image: null,
        label: 'U91310',
        value: 'U91310',
    },
    {
        badge: null,
        image: null,
        label: 'U91361',
        value: 'U91361',
    },
    {
        badge: null,
        image: null,
        label: 'U91363',
        value: 'U91363',
    },
    {
        badge: null,
        image: null,
        label: 'U91445',
        value: 'U91445',
    },
    {
        badge: null,
        image: null,
        label: 'U91472',
        value: 'U91472',
    },
    {
        badge: null,
        image: null,
        label: 'U91485',
        value: 'U91485',
    },
    {
        badge: null,
        image: null,
        label: 'U91490',
        value: 'U91490',
    },
    {
        badge: null,
        image: null,
        label: 'U91684',
        value: 'U91684',
    },
    {
        badge: null,
        image: null,
        label: 'U91685',
        value: 'U91685',
    },
    {
        badge: null,
        image: null,
        label: 'U91694',
        value: 'U91694',
    },
    {
        badge: null,
        image: null,
        label: 'U92101',
        value: 'U92101',
    },
    {
        badge: null,
        image: null,
        label: 'U92103',
        value: 'U92103',
    },
    {
        badge: null,
        image: null,
        label: 'U92117',
        value: 'U92117',
    },
    {
        badge: null,
        image: null,
        label: 'U92559',
        value: 'U92559',
    },
    {
        badge: null,
        image: null,
        label: 'U92650',
        value: 'U92650',
    },
    {
        badge: null,
        image: null,
        label: 'U92656',
        value: 'U92656',
    },
    {
        badge: null,
        image: null,
        label: 'U92658',
        value: 'U92658',
    },
    {
        badge: null,
        image: null,
        label: 'U92726',
        value: 'U92726',
    },
    {
        badge: null,
        image: null,
        label: 'U92727',
        value: 'U92727',
    },
    {
        badge: null,
        image: null,
        label: 'U92729',
        value: 'U92729',
    },
    {
        badge: null,
        image: null,
        label: 'U92730',
        value: 'U92730',
    },
    {
        badge: null,
        image: null,
        label: 'U92995',
        value: 'U92995',
    },
    {
        badge: null,
        image: null,
        label: 'U93108',
        value: 'U93108',
    },
    {
        badge: null,
        image: null,
        label: 'U93279',
        value: 'U93279',
    },
    {
        badge: null,
        image: null,
        label: 'U93358',
        value: 'U93358',
    },
    {
        badge: null,
        image: null,
        label: 'U93359',
        value: 'U93359',
    },
    {
        badge: null,
        image: null,
        label: 'U93577',
        value: 'U93577',
    },
    {
        badge: null,
        image: null,
        label: 'U93633',
        value: 'U93633',
    },
    {
        badge: null,
        image: null,
        label: 'U94061',
        value: 'U94061',
    },
    {
        badge: null,
        image: null,
        label: 'U94140',
        value: 'U94140',
    },
    {
        badge: null,
        image: null,
        label: 'U94303',
        value: 'U94303',
    },
    {
        badge: null,
        image: null,
        label: 'U94305',
        value: 'U94305',
    },
    {
        badge: null,
        image: null,
        label: 'U94369',
        value: 'U94369',
    },
    {
        badge: null,
        image: null,
        label: 'U94370',
        value: 'U94370',
    },
    {
        badge: null,
        image: null,
        label: 'U94439',
        value: 'U94439',
    },
    {
        badge: null,
        image: null,
        label: 'U94533',
        value: 'U94533',
    },
    {
        badge: null,
        image: null,
        label: 'U94867',
        value: 'U94867',
    },
    {
        badge: null,
        image: null,
        label: 'U95055',
        value: 'U95055',
    },
    {
        badge: null,
        image: null,
        label: 'U95057',
        value: 'U95057',
    },
    {
        badge: null,
        image: null,
        label: 'U95163',
        value: 'U95163',
    },
    {
        badge: null,
        image: null,
        label: 'U95335',
        value: 'U95335',
    },
    {
        badge: null,
        image: null,
        label: 'U95338',
        value: 'U95338',
    },
    {
        badge: null,
        image: null,
        label: 'U95457',
        value: 'U95457',
    },
    {
        badge: null,
        image: null,
        label: 'U95777',
        value: 'U95777',
    },
    {
        badge: null,
        image: null,
        label: 'U96040',
        value: 'U96040',
    },
    {
        badge: null,
        image: null,
        label: 'U96097',
        value: 'U96097',
    },
    {
        badge: null,
        image: null,
        label: 'U96143',
        value: 'U96143',
    },
    {
        badge: null,
        image: null,
        label: 'U96144',
        value: 'U96144',
    },
    {
        badge: null,
        image: null,
        label: 'U96145',
        value: 'U96145',
    },
    {
        badge: null,
        image: null,
        label: 'U96146',
        value: 'U96146',
    },
    {
        badge: null,
        image: null,
        label: 'U96147',
        value: 'U96147',
    },
    {
        badge: null,
        image: null,
        label: 'U96148',
        value: 'U96148',
    },
    {
        badge: null,
        image: null,
        label: 'U96354',
        value: 'U96354',
    },
    {
        badge: null,
        image: null,
        label: 'U96355',
        value: 'U96355',
    },
    {
        badge: null,
        image: null,
        label: 'U96417',
        value: 'U96417',
    },
    {
        badge: null,
        image: null,
        label: 'U96855',
        value: 'U96855',
    },
    {
        badge: null,
        image: null,
        label: 'U96856',
        value: 'U96856',
    },
    {
        badge: null,
        image: null,
        label: 'U96857',
        value: 'U96857',
    },
    {
        badge: null,
        image: null,
        label: 'U97215',
        value: 'U97215',
    },
    {
        badge: null,
        image: null,
        label: 'U97437',
        value: 'U97437',
    },
    {
        badge: null,
        image: null,
        label: 'U97525',
        value: 'U97525',
    },
    {
        badge: null,
        image: null,
        label: 'U98065',
        value: 'U98065',
    },
    {
        badge: null,
        image: null,
        label: 'U98077',
        value: 'U98077',
    },
    {
        badge: null,
        image: null,
        label: 'U98078',
        value: 'U98078',
    },
    {
        badge: null,
        image: null,
        label: 'U98160',
        value: 'U98160',
    },
    {
        badge: null,
        image: null,
        label: 'U98161',
        value: 'U98161',
    },
    {
        badge: null,
        image: null,
        label: 'U98599',
        value: 'U98599',
    },
    {
        badge: null,
        image: null,
        label: 'U98600',
        value: 'U98600',
    },
    {
        badge: null,
        image: null,
        label: 'U98601',
        value: 'U98601',
    },
    {
        badge: null,
        image: null,
        label: 'U98614',
        value: 'U98614',
    },
    {
        badge: null,
        image: null,
        label: 'U98981',
        value: 'U98981',
    },
    {
        badge: null,
        image: null,
        label: 'U99048',
        value: 'U99048',
    },
    {
        badge: null,
        image: null,
        label: 'U99049',
        value: 'U99049',
    },
    {
        badge: null,
        image: null,
        label: 'U99103',
        value: 'U99103',
    },
    {
        badge: null,
        image: null,
        label: 'U99406',
        value: 'U99406',
    },
    {
        badge: null,
        image: null,
        label: 'U99497',
        value: 'U99497',
    },
    {
        badge: null,
        image: null,
        label: 'U99831',
        value: 'U99831',
    },
    {
        badge: null,
        image: null,
        label: 'U99842',
        value: 'U99842',
    },
    {
        badge: null,
        image: null,
        label: 'UF7986',
        value: 'UF7986',
    },
    {
        badge: null,
        image: null,
        label: 'UM4094',
        value: 'UM4094',
    },
    {
        badge: null,
        image: null,
        label: 'UT7856',
        value: 'UT7856',
    },
];

export const MultiSelect = (args: MultiSelectProps): JSX.Element => (
    <div style={{ height: '1500px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <MultiSelectComponent {...args} />
    </div>
);

MultiSelect.args = {
    items: sampleItems,
    maxRows: 3,
    maxWidth: '20rem',
    onTermChange: undefined,
    size: 1,
} as MultiSelectProps;
